version: "3.9"

services:
  user-children-service:
    build: .
    container_name: user-children-service
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.interface.http.main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
